### ISSUE TITLE
Workflow fails on org project

### ISSUE THREAD

**Issue by chucksense** [takanabe/add-new-issues-to-project-column#23]
I get the following error:

`Error: /19 21:03:20 [ERROR] No such a project url: https://github.com/orgs/[redacted]/projects/1` (where of course `[redacted]` is my real org name).

Full trace and configuration for reference follows.

I've set up the personal access token as a secret as described.

### Full trace

```
Run takanabe/github-actions-automate-projects@v0.0.2
  env:
    GITHUB_TOKEN: ***
    GITHUB_PROJECT_URL: https://github.com/orgs/[redacted]/projects/1
    GITHUB_PROJECT_COLUMN_NAME: Triage
/usr/bin/docker run --name e5c355464d829fc2647d2b46cb9fe20b9b006_2bd3f5 --label 1e5c35 --workdir /github/workspace --rm -e GITHUB_TOKEN -e GITHUB_PROJECT_URL -e GITHUB_PROJECT_COLUMN_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/[redacted]/[redacted]":"/github/workspace" 1e5c35:5464d829fc2647d2b46cb9fe20b9b006
2020/10/19 21:03:19 [INFO] Event name: issues
2020/10/19 21:03:19 [INFO] Payload for issues extract correctly
Error: /19 21:03:20 [ERROR] No such a project url: https://github.com/orgs/[redacted]/projects/1
main.projectIDByOrg
	/app/main.go:197
main.main
	/app/main.go:64
runtime.main
	/usr/local/go/src/runtime/proc.go:200
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
```

### Config

```yaml
name: Auto assign and add to project

on:
    issues:
        types: [opened]

jobs:
    auto-assign-and-add-to-project:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  assignees: [redacted]
            - name: 'Add to project'
              uses: takanabe/github-actions-automate-projects@v0.0.2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITHUB_PROJECT_URL: https://github.com/orgs/[redacted]/projects/1
                GITHUB_PROJECT_COLUMN_NAME: Triage
```

The first step executes fine but the the step based on this one fails.  What am I doing wrong?
