### ISSUE TITLE
move issue to another column not working

### ISSUE THREAD

**Issue by bort2012** [takanabe/add-new-issues-to-project-column#30]
Hi, 

I try to move an issue to another column when it is closed. The action runs succesfully but the column does not change.
But I can see this message in the log:

```
2021/06/09 23:36:50 [INFO] Event name: issues
2021/06/09 23:36:50 [INFO] GitHub action interupts!!
2021/06/09 23:36:50 [INFO] This issue is not new one :D
```

Has someone had this problem?

Here is my config:

```
name: add-closed-issues-to-acceptance-test
on: [issues]
jobs:
  add-closed-issues-to-acceptance-test:
    runs-on: ubuntu-latest
    steps:
    - name: add-closed-issues-to-acceptance-test
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/orgs/company/projects/3
        GITHUB_PROJECT_COLUMN_NAME: Acceptance test
```
